### PR TITLE
update aiofiles dep, add maintainer collective, pip check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- unblocks https://github.com/conda-forge/jupyter_server_ydoc-feedstock/pull/15
- adds `pip check`
- adds `jupyter_server` maintainers :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/ypy-websocket ready for review. Also opened some issues upstream that would help in robustly packaging this for conda-forge.

**Comment by davidbrochart** [comment]
Thanks again @bollwyvl.
It looks like we're starting to run tests in conda-forge now? IIRC that was not the case previously.

**Comment by bollwyvl** [comment]
> run tests in conda-forge

Basically once I see a a problematic release (version mismatch, missing files, etc), it is a better use of maintainer and end user time to pay the up-front cost to get another set of bots going after the product-as-deployed: especially in a single- (or only triple-)build `noarch` feedstocks, the marginal cost is not that great compared to having to do triage feedstock (or worse, upstream) issues, `broken` requests, repodata patches, etc.

Even if the conda-forge build environment has its own quirks (docker, etc), it helps normalize the overall conda-forge offering in the face of ever-changing "clever" upstream build systems, upstream CI regimes, etc.

**Pull request merged**
